# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackathon2022' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hackathon2022
	pod 'Alamofire'


end
